# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcb6bb3e1551095373daf5ce46c7ba84409c822f154283fc2389c5f0744845339993566b5fb23987a68736411b83945d249698f90db07067d109fd4e7b75ae0f

test:
  secret_key_base: 673807d423893f6f44cf749eb751beddad7cb6146caf59c52f5515d7125dbf4018cab6c3f88bd663cfd596dedbf6439d46132fdda1374bd4f6a618be79ced0aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
